# NumPy

In [ ]:
import numpy as np

## Create an Array
Write a Python program that creates an integer array with 4 elements of type unsigned int16 and prints the shape, the number of dimensions, and the length of each element in bytes.

In [1]:
import numpy as np

# Create an integer array with 4 elements of type unsigned int16
array = np.array([1, 2, 3, 4], dtype=np.uint16)

# Print the shape of the array
print("Shape of the array:", array.shape)

# Print the number of dimensions of the array
print("Number of dimensions:", array.ndim)

# Print the length of each element in bytes
print("Length of each element in bytes:", array.itemsize)


Shape of the array: (4,)
Number of dimensions: 1
Length of each element in bytes: 2


## Create a 2D Array
Write a Python program that creates a $ 5 \times 2 $ integer array from a range between 100 to 200 such that the difference between each element is 10.

In [2]:
import numpy as np

# Create an array with a range from 100 to 200 with a step of 10
array = np.arange(100, 200, 10)

# Reshape the array to 5x2
array_2d = array.reshape(5, 2)

# Print the array
print("2D Array:")
print(array_2d)


2D Array:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


## Select Rows and Columns
Write a Python program to return the 2D array of odd rows and even columns from the given numpy array.

In [ ]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a

In [14]:
# Original array

a = np.array([[3, 6, 9, 12], [15, 18, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 60]])
print("Original array:")
print(a)


Original array:
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


# Selecting Odd Rows and Even Columns

*   Odd Rows: Rows with indices 0, 2, 4, etc.
*   Even Columns: Columns with indices 0, 2, etc.


In [15]:
# use slicing to select the desired rows and columns:

# Select odd rows (rows with indices 1, 3, 5, etc.)
odd_rows = a[::2]

# Select even columns (columns with indices 0, 2, etc.)
result = odd_rows[:, ::2]

print("\n2D array with odd rows and even columns:")
print(result)


2D array with odd rows and even columns:
[[ 3  9]
 [27 33]
 [51 57]]


# Combining everything => Complete Program

In [16]:
# Original array
a = np.array([[3, 6, 9, 12], [15, 18, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 60]])
print("Original array:")
print(a)

# Select odd rows (rows with indices 0, 2, 4, etc.)
odd_rows = a[::2]

# Select even columns (columns with indices 0, 2, etc.)
result = odd_rows[:, ::2]

print("\n2D array with odd rows and even columns:")
print(result)


Original array:
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

2D array with odd rows and even columns:
[[ 3  9]
 [27 33]
 [51 57]]


## Compute Numerical Operations
Write a Python program that computes the sum, the element-wise multiplication, and the matrix multiplication of the given numpy arrays.

In [ ]:
a = np.array([[5, 6], [21, 18]])
b = np.array([[15, 33], [4, 7]])
a, b

# Given Arrays

In [17]:
a = np.array([[5, 6], [21, 18]])
b = np.array([[15, 33], [4, 7]])

print("Array a:")
print(a)
print("\nArray b:")
print(b)


Array a:
[[ 5  6]
 [21 18]]

Array b:
[[15 33]
 [ 4  7]]


# Computing the Sum

*   The sum of the two arrays is computed element-wise.List item

In [21]:
# Compute the sum
sum_arrays = a + b
print("\nSum of a and b:")
print(sum_arrays)



Sum of a and b:
[[20 39]
 [25 25]]


# Computing the Element-Wise Multiplication

*   The element-wise multiplication of the two arrays is computed by multiplying corresponding elements.

In [19]:
# Compute the element-wise multiplication
elementwise_mul = a * b
print("\nElement-wise multiplication of a and b:")
print(elementwise_mul)



Element-wise multiplication of a and b:
[[ 75 198]
 [ 84 126]]


# Computing the Matrix Multiplication
* Matrix multiplication is performed using the dot product.

In [18]:
# Compute the matrix multiplication
matrix_mul = np.dot(a, b)
print("\nMatrix multiplication of a and b:")
print(matrix_mul)



Matrix multiplication of a and b:
[[ 99 207]
 [387 819]]


# Combining everything => Complete Program

In [20]:
# Given arrays
a = np.array([[5, 6], [21, 18]])
b = np.array([[15, 33], [4, 7]])

print("Array a:")
print(a)
print("\nArray b:")
print(b)

# Compute the sum
sum_arrays = a + b
print("\nSum of a and b:")
print(sum_arrays)

# Compute the element-wise multiplication
elementwise_mul = a * b
print("\nElement-wise multiplication of a and b:")
print(elementwise_mul)

# Compute the matrix multiplication
matrix_mul = np.dot(a, b)
print("\nMatrix multiplication of a and b:")
print(matrix_mul)


Array a:
[[ 5  6]
 [21 18]]

Array b:
[[15 33]
 [ 4  7]]

Sum of a and b:
[[20 39]
 [25 25]]

Element-wise multiplication of a and b:
[[ 75 198]
 [ 84 126]]

Matrix multiplication of a and b:
[[ 99 207]
 [387 819]]


## Split and Concatenate an Array
Write a Python program to split the given $ 8 \times 3 $ array into 4 equal-sized $ 2 \times 3 $ sub-arrays. Then, concatenate the splitted arrays vertically to rebuilt the original array.

In [ ]:
a = np.arange(10, 34, 1).reshape(8, 3)
a

# Step 1: Create the Original Array

In [10]:
# Create the 8×3 array from a range between 10 to 34
a = np.arange(10, 34).reshape(8, 3)
print("Original array:")
print(a)


Original array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


# Step 2: Split the Array into Four 2×3 Sub-Arrays

In [11]:
# Split the array into four 2×3 sub-arrays
sub_arrays = np.split(a, 4)
print("\nSplitted sub-arrays:")
for sub_array in sub_arrays:
    print(sub_array)



Splitted sub-arrays:
[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]


# Step 3: Concatenate the Sub-Arrays Vertically to Rebuild the Original Array

In [12]:
# Concatenate the sub-arrays vertically
reconstructed_array = np.vstack(sub_arrays)
print("\nReconstructed array:")
print(reconstructed_array)



Reconstructed array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


# Combining everything => Complete Program

In [13]:
# Create the 8×3 array from a range between 10 to 34
a = np.arange(10, 34).reshape(8, 3)
print("Original array:")
print(a)

# Split the array into four 2×3 sub-arrays
sub_arrays = np.split(a, 4)
print("\nSplitted sub-arrays:")
for sub_array in sub_arrays:
    print(sub_array)

# Concatenate the sub-arrays vertically
reconstructed_array = np.vstack(sub_arrays)
print("\nReconstructed array:")
print(reconstructed_array)


Original array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Splitted sub-arrays:
[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]

Reconstructed array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


## Replace a Column
Write a Python program that replaces the second column from the given array with the new given column.

In [ ]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
new_column = np.array([[10, 10, 10]])
a, new_column

# Original Array

In [7]:
# Given array and the new column
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
new_column = np.array([10, 10, 10])

print("Original array:")
print(a)
print("\nNew column to be inserted:")
print(new_column)


Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

New column to be inserted:
[10 10 10]


# Replace the second column of a with the new_column

In [8]:
# Replace the second column
a[:, 1] = new_column

print("\nArray after replacing the second column:")
print(a)



Array after replacing the second column:
[[34 10 73]
 [82 10 12]
 [53 10 66]]


# Combining Everything

In [9]:
# Original array
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
new_column = np.array([10, 10, 10])

print("Original array:")
print(a)

print("\nNew column to be inserted:")
print(new_column)

# Replace the second column
a[:, 1] = new_column

print("\nArray after replacing the second column:")
print(a)


Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

New column to be inserted:
[10 10 10]

Array after replacing the second column:
[[34 10 73]
 [82 10 12]
 [53 10 66]]


## Sort Rows and Columns
Write a Python program to sort the given 2D array in 2 scenarios: (1) Sort the rows; (2) Sort the columns.  

In [ ]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
a

# Original Array

In [3]:
#Here's the given array:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print("Original array:")
print(a)


Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]


#Sorting the Rows

In [4]:
#Sorting the Rows
sorted_rows = np.sort(a, axis=1)
print("\nArray with sorted rows:")
print(sorted_rows)




Array with sorted rows:
[[34 43 73]
 [12 22 82]
 [53 66 94]]


# Sorting Each Column

In [5]:
# Sort each column
sorted_columns = np.sort(a, axis=0)
print("\nArray with sorted columns:")
print(sorted_columns)



Array with sorted columns:
[[34 22 12]
 [53 43 66]
 [82 94 73]]


# Combining Everything

In [6]:
# Original array
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print("Original array:")
print(a)

# Sort each row
sorted_rows = np.sort(a, axis=1)
print("\nArray with sorted rows:")
print(sorted_rows)

# Sort each column
sorted_columns = np.sort(a, axis=0)
print("\nArray with sorted columns:")
print(sorted_columns)


Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Array with sorted rows:
[[34 43 73]
 [12 22 82]
 [53 66 94]]

Array with sorted columns:
[[34 22 12]
 [53 43 66]
 [82 94 73]]
